export interface Partner {
  name: string;
  category: "international" | "mobile" | "card";
  description: string;
  speed: string;
  countries: string[];
  color: string;
  textColor?: string;
}

export const partners: Partner[] = [
  {
    name: "Western Union",
    category: "international",
    description: "The world's largest money transfer network — send and receive in minutes to 200+ countries.",
    speed: "Minutes",
    countries: ["UK", "USA", "Europe", "Canada", "Australia", "Asia", "Africa", "200+ countries"],
    color: "#f5a623",
  },
  {
    name: "Ria Money Transfer",
    category: "international",
    description: "Low-fee international transfers with competitive exchange rates to 165+ countries.",
    speed: "Minutes",
    countries: ["UK", "USA", "Spain", "France", "Italy", "Germany", "165+ countries"],
    color: "#e31837",
    textColor: "#ffffff",
  },
  {
    name: "MoneyGram",
    category: "international",
    description: "Fast and reliable money transfers to 200+ countries and territories worldwide.",
    speed: "Minutes",
    countries: ["UK", "USA", "Europe", "Middle East", "Asia", "200+ countries"],
    color: "#eb0000",
    textColor: "#ffffff",
  },
  {
    name: "PRIMR Money",
    category: "international",
    description: "Affordable remittance solution focused on Africa-Europe corridors.",
    speed: "Minutes",
    countries: ["UK", "France", "Belgium", "Netherlands", "Germany", "Italy"],
    color: "#1B2A87",
    textColor: "#ffffff",
  },
  {
    name: "ACE Money Transfer",
    category: "international",
    description: "Trusted by millions for sending money to South Asia and beyond.",
    speed: "Minutes",
    countries: ["UK", "Europe", "Pakistan", "India", "Bangladesh", "Nepal"],
    color: "#003087",
    textColor: "#ffffff",
  },
  {
    name: "Soni Transfer",
    category: "international",
    description: "Specialized in West Africa corridors with competitive rates.",
    speed: "Same Day",
    countries: ["UK", "France", "Spain", "Italy", "West Africa"],
    color: "#ff6600",
    textColor: "#ffffff",
  },
  {
    name: "Ping Money Transfer",
    category: "international",
    description: "Digital-first money transfer service with low fees.",
    speed: "Minutes",
    countries: ["UK", "USA", "Europe", "Canada", "Australia"],
    color: "#0072ce",
    textColor: "#ffffff",
  },
  {
    name: "Trans-Fast",
    category: "international",
    description: "Global money transfer with a focus on speed and reliability.",
    speed: "Minutes",
    countries: ["USA", "Canada", "Europe", "Philippines", "India", "Mexico"],
    color: "#cc0000",
    textColor: "#ffffff",
  },
  {
    name: "BnG Money Transfer",
    category: "international",
    description: "Community-focused transfer service for West African diaspora.",
    speed: "Minutes",
    countries: ["UK", "France", "Germany", "Netherlands", "West Africa"],
    color: "#006400",
    textColor: "#ffffff",
  },
  {
    name: "Wave",
    category: "mobile",
    description: "Africa's fastest growing mobile money platform. Deposit and withdraw instantly.",
    speed: "Instant",
    countries: ["The Gambia", "Senegal", "Ivory Coast", "Cameroon", "Uganda"],
    color: "#00b9f1",
  },
  {
    name: "Orange Money",
    category: "mobile",
    description: "Orange telecom's mobile money service for instant local and regional transfers.",
    speed: "Instant",
    countries: ["The Gambia", "Senegal", "Mali", "Guinea", "Ivory Coast"],
    color: "#ff6600",
    textColor: "#ffffff",
  },
  {
    name: "Taybull PAY",
    category: "mobile",
    description: "Local mobile payment solution for The Gambia.",
    speed: "Instant",
    countries: ["The Gambia"],
    color: "#1B2A87",
    textColor: "#ffffff",
  },
  {
    name: "NAFA Money Transfer",
    category: "mobile",
    description: "Local Gambian mobile money agent — deposit and withdraw with ease.",
    speed: "Instant",
    countries: ["The Gambia"],
    color: "#003087",
    textColor: "#ffffff",
  },
  {
    name: "Visa",
    category: "card",
    description: "Accepted for card payments and cash advances.",
    speed: "Instant",
    countries: ["Worldwide"],
    color: "#1a1f71",
    textColor: "#ffffff",
  },
  {
    name: "Mastercard",
    category: "card",
    description: "Accepted for card payments and cash advances.",
    speed: "Instant",
    countries: ["Worldwide"],
    color: "#eb001b",
    textColor: "#ffffff",
  },
];
